service: idream-auth-service

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  region: "us-east-1"
  environment:
    AUTH0_PUBLIC_KEY: ${file(secret.pem)}

functions:
  auth:
    handler: app/handler.auth
    cors: true
  publicEndpoint:
    handler: app/handler.publicEndpoint
    events:
      - http:
          path: public
          method: POST
          cors: true
  privateEndpoint:
    handler: app/handler.privateEndpoint
    events:
      - http:
          path: private
          method: POST
          authorizer: auth
          cors: true

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
    AuthFailureGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
